# Generated by Django 3.2.7 on 2021-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading1', models.CharField(max_length=500)),
                ('content1', models.CharField(max_length=5000)),
                ('heading2', models.CharField(max_length=500)),
                ('content2', models.CharField(max_length=5000)),
                ('heading3', models.CharField(max_length=500)),
                ('content3', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
